การควบคุมเหมาะที่สุดและการเรียนรูู้เสริมกำลัง -- ดร.วโรดม ตู้จินดา

# ภาคผนวก B รวมเคล็ดลับภาษาไพทอน

ในภาคผนวกนี้เป็นการรวบรวมเคล็ดลับภาษาไพทอนที่ใช้ในหนังสือ 


## B.1 การตัดเฉือนเมทริกซ์เป็นเวกเตอร์

การตัดเฉือนเมทริกซ์เป็นเวกเตอร์โดยคงความเป็นสองมิติไว้ สมมุติว่ามีเมทริกซ์ขนาด 2 x 3 


In [1]:
import numpy as np

In [2]:
M = np.random.rand(2,3) 
M.shape

(2, 3)

ต้องการตัดเวกเตอร์คอลัมน์แรกมาใช้งาน หากใช้ M[:,0] จะพบว่ารูปเป็นแบบ (2,) ไม่ใช่ (2,1) 

In [3]:
cvec0 = M[:,0]
cvec0.shape

(2,)

ซึ่งเมื่อนำไปคำนวณในสมการเมทริกซ์อาจทำให้ผลไม่ถูกต้องจากการแพร่ (broadcast) 
หากต้องการให้ยังคงรูปสองมิติไว้ ต้องครอบตัวชี้ของมิติที่สองโดย [] ดังนี้

In [4]:
cvec1 = M[:,[0]]
cvec1.shape

(2, 1)

## B.2 เมทริกซ์แคลคูลัส

รวมวิธีการที่ใช้ในบทที่ 5 เพื่อหลีกเลี่ยงการคำนวณโดยใช้เทนเซอร์

สำหรับฟังก์ชัน $f(x) : \mathbb{R}^n \rightarrow \mathbb{R}^m$ เมื่อพิจารณาการกระจายเทเลอร์อันดับสอง 

กรณี $m=1$ :
$$
f(x + \Delta x) \approx f(x) + \frac{\partial f}{\partial x}\Delta x 
+ \frac{1}{2}\Delta x^T \frac{\partial^2 f}{\partial x^2}\Delta x \tag{B.1}
$$

โดย $\frac{\partial f}{\partial x}$ เป็นเวกเตอร์ขนาด $1 \times n$ และ $\frac{\partial^2 f}{\partial x^2}$ 
เป็นเมทริกซ์ขนาด $n \times n$ 

กรณี $m \gt 1$ :
$$
f(x + \Delta x) \approx f(x) + \frac{\partial f}{\partial x}\Delta x 
+ \frac{1}{2}\Delta x^T \frac{\partial^2 f}{\partial x^2}\Delta x \tag{B.2}
$$
เมื่อกระจายพจน์สุดท้ายด้านขวา
$$
\frac{1}{2}\Delta x^T \frac{\partial^2 f}{\partial x^2}\Delta x = 
\frac{1}{2} \Big( \frac{\partial}{\partial x}\Big[ \frac{\partial f}{\partial x}\Delta x \Big] \Big) \Delta x \tag{B.3}
$$
จะเห็นได้ว่าเป็นเทนเซอร์ 3 มิติ แม้ว่าจะมีแพ็กเกจเฉพาะรองรับการคำนวณโดยเทนเซอร์ได้ แต่หากต้องการใช้แพ็กเกจทั่วไปเช่น numpy, scipy หรือการคำนวณอนุพันธ์อัตโนมัติ จะต้องมีกลเม็ดในการแปลงเทนเซอร์ให้เป็นเมทริกซ์ 2 มิติ โดยใช้การดำเนินการต่อไปนี้

#### ผลคูณโครเนคเกอร์ 

ผลคูณโครเนคเกอร์​ (Kronecker product) ของเมทริกซ์ $A$ ขนาด $l \times m$ และ $B$ ขนาด $n \times p$ เขียนแทนโดย
$A \otimes B$ คือเมทริกซ์บล็อกขนาด $ln \times mp$ ที่เกิดจากการคูณสมาชิกทุกตัวของ $A$ กับเมทริกซ์ $B$ 
$$
A \otimes B = 
\left[\begin{array}{cccc}
a_{11}B & a_{12}B & \cdots & a_{1m}B \\
a_{21}B & a_{22}B & \cdots & a_{2m}B \\
\vdots & \vdots & \ddots & \vdots \\
a_{l1}B & a_{l2}B & \cdots & a_{lm}B
\end{array}\right] \tag{B.4}
$$

ในบทที่ 3,4 ได้มีการใช้ผลคูณโครเนคเกอร์เพิ่มความสะดวกในการจัดรูปเมทริกซ์สำหรับปัญหา QP ที่มีลักษณะเป็นบล็อกทแยงมุม 

#### การแปลงเป็นเวกเตอร์

กำหนดเมทริกซ์ $A$ ขนาด $l \times m$ เขียนแยกคอลัมน์ได้เป็น
$$
A = 
\left[\begin{array}{ccccc}
A_1 & A_2 & A_3 & \cdots &A_m
\end{array}\right] \tag{B.5}
$$
การแปลงเป็นเวกเตอร์ (vectorization) เขียนแทนโดย $vec(A)$ จะให้ผลเป็นเวกเตอร์คอลัมน์ดังนี้
$$
vec(A) = 
\left[\begin{array}{c}
A_1 \\
A_2 \\
A_3 \\
\vdots \\
A_m
\end{array}\right] \tag{B.6}
$$

เมื่อใช้ผลคูณโครเนคเกอร์ร่วมกับการแปลงเป็นเวกเตอร์ จะได้เป็นกลเม็ดเวกเตอร์ดังนี้
$$
vec(ABC) = (C^T \otimes A)vec(B) \tag{B.7}
$$
สามารถใช้ในการแปลงผลคูณเมทริกซ์เป็นเวกเตอร์ ตัวอย่างเช่น
$$
vec(AB) = (B^T \otimes I)vec(A) = (I \otimes A) vec(B) \tag{B.8}
$$

ดังนั้นในการหาอนุพันธ์ของเมทริกซ์เทียบกับเวกเตอร์ เราสามารถหลีกเลี่ยงผลลัพธ์เป็นเทนเซอร์ได้โดยแปลงเมทริกซ์เป็นเวกเตอร์ก่อน
$$
\frac{\partial A(x)}{\partial x} = \frac{\partial vec(A)}{\partial x} \tag{B.9}
$$
ซึ่งจะได้ผลลัพธ์เป็นเมทริกซ์ขนาด $lm \times n$ เราจะใช้วิธีการนี้ทุกครั้งที่หาอนุพันธ์เมทริกซ์ 

ในกรณีที่ต้องการหาอนุพันธ์ผ่านการสลับเปลี่ยน จะใช้เมทริกซ์ $T$ ที่เรียกว่า ตัวสลับเปลี่ยน (commutator)
$$
\frac{\partial} {\partial x}(A^T(x)B) = (B^T \otimes I)T\frac{\partial A(x)}{\partial x} \tag{B.10}
$$
โดย
$$
Tvec(A) = vec(A^T) \tag{B.11}
$$

เราสามารถเขียนฟังก์ชัน vec() โดยภาษาไพทอนได้หลายรูปแบบ ตัวอย่างหนึ่งคือ

In [1]:
import numpy as np

def vec(Mat):
    m, n = np.shape(Mat)[0], np.shape(Mat)[1]
    return np.reshape(Mat,(m*n,1), order='F')

In [2]:
vec(np.eye(3))

array([[1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.]])

สำหรับเมทริกซ์ตัวสลับเปลี่ยน $T$ สามารถเขียนฟังก์ชันดังนี้

In [3]:
from scipy.sparse import csr_matrix
def comm(M):
    m, n = M.shape[0], M.shape[1]
    row  = np.arange(m*n)
    col  = row.reshape((m, n), order='F').ravel()
    data = np.ones(m*n, dtype=np.int8)
    T = csr_matrix((data, (row, col)), shape=(m*n, m*n))
    return T.toarray()

สังเกตว่าในการใช้งาน เมทริกซ์ $T$ จะเป็นค่าคงที่ขึ้นอยู่กับขนาดของเมทริกซ์ $A$ ใน (B.11) 
ดังนั้นเราคำนวณเพียงครั้งเดียวแล้วใช้เมทริกซ์ค่าคงที่นั้นในการวนซ้ำ

In [4]:
Nx = 4 # number of states
A = np.random.rand(Nx,Nx)
T = comm(A)
T

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

**ทางเลือก**

ในการหาอนุพันธ์อัตโนมัติโดยใช้แพ็กเกจเช่น JAX การคำนวณอนุพันธ์ต้องผ่านฟังก์ชัน vec() 
ซึ่งจากการทดสอบพบว่าไม่สามารถทำงานได้ เราจึงเสนออีกทางเลือกหนึ่งคือคำนวณเฮสเซียนกับเมทริกซ์ 
$A$ โดยไม่ต้องแปลงเป็นเวกเตอร์ เมื่อได้เอาต์พุตเป็นเทนเซอร์จึงแปลงเทนเซอร์นั้นเป็นเมทริกซ์ 
ซึ่งการดำเนินการนี้เราต้องทราบว่าแต่ละสมาชิกของเทนเซอร์ที่ได้จากการคำนวณเฮสเซียนคือ 
$\frac{\partial^2 f_i}{\partial x_j \partial x_k}$ 
คืออนุพันธ์ของฟังก์ชัน $f_i$ เทียบกับอินพุต $x_j$ และ $x_k$ ซึ่งสามารถเข้าใจได้ไม่ยาก
ฟังก์ชัน tensormat() ด้านล่างนี้จะให้เอาต์พุตเป็นเมทริกซ์ที่สอดคล้องกับการใช้ vec() 
มีข้อดีคือเรียกฟังก์ชันนี้หลังจากการหาอนุพันธ์อัตโนมัติเสร็จสิ้นแล้วทำให้ไม่เกิดปัญหาการใช้งาน

In [5]:
def tensor2mat(Mat3d):
    dim3 = Mat3d.shape[2]
    M = Mat3d[:,:,0]
    for i in range(dim3-1):
        M = np.vstack((M,Mat3d[:,:,i+1]))
    return M

In [8]:
H = np.zeros((3,3,3))
for k in range(3):
    H[:,:,k] = np.eye(3)
tensor2mat(H)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<div align="center">
<img src="https://raw.githubusercontent.com/dewdotninja/sharing-github/refs/heads/master/dewninja_logo50.jpg" alt="dewninja"/>
</div>
<div align="center">dew.ninja 2025</div>